//projecteuler2

// sum of even fibonacci numbers

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

// my solution

#include <iostream>
using namespace std;

int genNextFib(int first, int second);

int main()
{
	int limit = 4000000;	// 4 million
	int first = 0; int second = 1;
	int next = 0; int sum = 0;
	while(next < limit)
	{
		// generate fibonacci sequence
		next = genNextFib(first, second);
		// begin to sum even numbers in sequence
		if(next%2==0)
			sum += next;
		// iterate through the sequence
		first = second;
		second = next;
	}
	cout<<sum<<endl;

	return 0;
}

int genNextFib(int first, int second)
{
	return(first + second);
}